#!/usr/bin/env bash
# download-tests.sh — Downloads all 102 test files from the repo branch.
# Run from inside the `backend/` directory:
#   curl -fsSL "https://raw.githubusercontent.com/MSHH88/BookingAutomation/copilot/create-detailed-automation-plan/backend/scripts/download-tests.sh" | bash

set -euo pipefail

BASE="https://raw.githubusercontent.com/MSHH88/BookingAutomation/copilot/create-detailed-automation-plan/backend"

dl() {
  local n="$1" path="$2"
  curl -fsSL --create-dirs -o "$path" "$BASE/$path" && printf "OK  %3d/102  %s\n" "$n" "$path" || printf "FAIL %3d/102  %s\n" "$n" "$path"
}

dl   1 "src/config/businessType.test.ts"
dl   2 "src/jobs/ai-suggestion.job.test.ts"
dl   3 "src/jobs/birthday.job.test.ts"
dl   4 "src/jobs/no-show.job.test.ts"
dl   5 "src/jobs/rebook-nudge.job.test.ts"
dl   6 "src/lib/pricing-engine.test.ts"
dl   7 "src/middleware/auth.test.ts"
dl   8 "src/middleware/requireLeadAccess.test.ts"
dl   9 "src/modules/admin/admin.service.test.ts"
dl  10 "src/modules/ai/ai.service.test.ts"
dl  11 "src/modules/alerts/alerts.service.test.ts"
dl  12 "src/modules/alerts/alerts.test.ts"
dl  13 "src/modules/analytics/analytics.service.test.ts"
dl  14 "src/modules/analytics/analytics.test.ts"
dl  15 "src/modules/artists/artist-media.service.test.ts"
dl  16 "src/modules/artists/artists.test.ts"
dl  17 "src/modules/auth/auth.service.test.ts"
dl  18 "src/modules/auth/auth.test.ts"
dl  19 "src/modules/availability/availability.service.test.ts"
dl  20 "src/modules/availability/availability.test.ts"
dl  21 "src/modules/booking-photos/booking-photos.service.test.ts"
dl  22 "src/modules/booking-photos/booking-photos.test.ts"
dl  23 "src/modules/bookings/bookings.service.test.ts"
dl  24 "src/modules/bookings/bookings.test.ts"
dl  25 "src/modules/calendar/apple-calendar.service.test.ts"
dl  26 "src/modules/calendar/calendar.service.test.ts"
dl  27 "src/modules/calendar/calendar.test.ts"
dl  28 "src/modules/calendar/outlook-calendar.service.test.ts"
dl  29 "src/modules/campaigns/campaigns.service.test.ts"
dl  30 "src/modules/campaigns/campaigns.test.ts"
dl  31 "src/modules/capture/capture.service.test.ts"
dl  32 "src/modules/customer-stats/customer-stats.service.test.ts"
dl  33 "src/modules/customer-stats/customer-stats.test.ts"
dl  34 "src/modules/customers/customers.service.test.ts"
dl  35 "src/modules/email-templates/email-templates.service.test.ts"
dl  36 "src/modules/email-templates/email-templates.test.ts"
dl  37 "src/modules/features/features.test.ts"
dl  38 "src/modules/forms/forms.service.test.ts"
dl  39 "src/modules/forms/forms.test.ts"
dl  40 "src/modules/gift-cards/gift-cards.service.test.ts"
dl  41 "src/modules/gift-cards/gift-cards.test.ts"
dl  42 "src/modules/health-flags/health-flags.service.test.ts"
dl  43 "src/modules/health-flags/health-flags.test.ts"
dl  44 "src/modules/invoices/invoices.service.test.ts"
dl  45 "src/modules/invoices/invoices.test.ts"
dl  46 "src/modules/leads/leads.service.test.ts"
dl  47 "src/modules/leads/leads.test.ts"
dl  48 "src/modules/locations/locations.test.ts"
dl  49 "src/modules/loyalty/loyalty.service.test.ts"
dl  50 "src/modules/loyalty/loyalty.test.ts"
dl  51 "src/modules/memberships/memberships.service.test.ts"
dl  52 "src/modules/memberships/memberships.test.ts"
dl  53 "src/modules/notifications/notifications.service.test.ts"
dl  54 "src/modules/packages/packages.service.test.ts"
dl  55 "src/modules/packages/packages.test.ts"
dl  56 "src/modules/payments/payments.service.test.ts"
dl  57 "src/modules/payments/payments.test.ts"
dl  58 "src/modules/payroll/payroll.service.test.ts"
dl  59 "src/modules/payroll/payroll.test.ts"
dl  60 "src/modules/pos/pos.service.test.ts"
dl  61 "src/modules/pos/pos.test.ts"
dl  62 "src/modules/pricing/pricing.test.ts"
dl  63 "src/modules/products/products.service.test.ts"
dl  64 "src/modules/products/products.test.ts"
dl  65 "src/modules/public/public.service.test.ts"
dl  66 "src/modules/public/public.test.ts"
dl  67 "src/modules/push/push.service.test.ts"
dl  68 "src/modules/quotes/quotes.service.test.ts"
dl  69 "src/modules/quotes/quotes.test.ts"
dl  70 "src/modules/recurring-bookings/recurring-bookings.service.test.ts"
dl  71 "src/modules/recurring-bookings/recurring-bookings.test.ts"
dl  72 "src/modules/referrals/referrals.service.test.ts"
dl  73 "src/modules/referrals/referrals.test.ts"
dl  74 "src/modules/reminders/reminders.queue.test.ts"
dl  75 "src/modules/reviews/reviews.queue.test.ts"
dl  76 "src/modules/roles/roles.service.test.ts"
dl  77 "src/modules/roles/roles.test.ts"
dl  78 "src/modules/rota/rota.service.test.ts"
dl  79 "src/modules/rota/rota.test.ts"
dl  80 "src/modules/services/services.service.test.ts"
dl  81 "src/modules/services/services.test.ts"
dl  82 "src/modules/sessions/sessions.test.ts"
dl  83 "src/modules/settings/settings.service.test.ts"
dl  84 "src/modules/settings/settings.test.ts"
dl  85 "src/modules/sms-templates/sms-templates.service.test.ts"
dl  86 "src/modules/sms-templates/sms-templates.test.ts"
dl  87 "src/modules/social/social.service.test.ts"
dl  88 "src/modules/social/social.test.ts"
dl  89 "src/modules/styles/styles.service.test.ts"
dl  90 "src/modules/styles/styles.test.ts"
dl  91 "src/modules/tables/tables.service.test.ts"
dl  92 "src/modules/tenants/tenants.service.test.ts"
dl  93 "src/modules/tenants/tenants.test.ts"
dl  94 "src/modules/uploads/uploads.service.test.ts"
dl  95 "src/modules/uploads/uploads.test.ts"
dl  96 "src/modules/waitlist/waitlist.service.test.ts"
dl  97 "src/modules/waitlist/waitlist.test.ts"
dl  98 "src/modules/webhooks/webhooks.service.test.ts"
dl  99 "src/modules/whatsapp-templates/whatsapp-templates.service.test.ts"
dl 100 "src/modules/whatsapp-templates/whatsapp-templates.test.ts"
dl 101 "src/modules/whatsapp/whatsapp.queue.test.ts"
dl 102 "src/modules/whatsapp/whatsapp.service.test.ts"

echo ""
echo "✅  All 102 test files downloaded."
